import random
from datetime import datetime, timedelta
import csv

# Function to generate random datetime strings within a range of months and days
def random_date(start, end):
    random_days = random.randint(0, (end - start).days)
    return (start + timedelta(days=random_days)).strftime('%Y-%m-%d')

# Start and end datetime for generating random times
start_time = datetime(2022, 1, 1)
end_time = datetime(2024, 12, 31)

# List of functions to be used
functions = [
    "onGenerateFibulaPlanesTimerTimeout",
    "makeBooleanOperationsToFibulaSurgicalGuideBase",
    "sendFunctionCountToServer",
    "initializeSystemDiagnostics",
    "updateFirmwareVersions",
    "calculateOptimalPathways",
    "archiveOldLogFiles",
    "monitorNetworkLatency",
    "generateEncryptionKeys",
    "validateUserPermissions",
    "optimizeDatabaseQueries",
    "deploySoftwareUpdates",
    "auditSecurityCompliance",
    "scheduleSystemBackups",
    "analyzeServerPerformance",
    "configureVirtualMachines",
    "restoreArchivedData",
    "trackApplicationDependencies",
    "manageResourceAllocation",
    "simulateLoadBalancing",
    "verifyDataIntegrity",
    "cleanTemporaryFiles",
    "reportSystemHealthStatus"
]

# List of medical module names
modules = [
    "CardiovascularAssessmentTool",
    "NeuralNetworkDiagnostics",
    "OrthopedicProcedureSimulator",
    "PediatricCareAssistant",
    "OphthalmologyVisionAnalyzer",
    "GastrointestinalTracker",
    "EndocrineHealthMonitor",
    "PulmonaryFunctionTester",
    "DermatologyTreatmentPlanner",
    "NeurosurgeryNavigationSystem",
    "HematologyAnalyzer",
    "InfectiousDiseaseMapper",
    "RadiologyImagingCenter",
    "UrologyManagementSystem",
    "ObstetricsLaborTracker",
    "GeneticDisorderExplorer",
    "ImmunologyResponseEvaluator",
    "OncologyTreatmentOptimizer",
    "EmergencyResponseCoordinator",
    "MentalHealthTherapyAssistant",
    "RehabilitationExercisePlanner",
    "PainManagementAdvisor",
    "SleepDisorderAnalyzer",
    "AllergyReactionTracker",
    "DentalHealthProfiler",
    "NutritionAndDietPlanner",
    "FitnessAndWellnessGuide",
    "BloodPressureRegulator",
    "DiabetesCareManager",
    "WoundCareToolkit",
    "SubstanceAbuseCounselor",
    "GeriatricCarePlanner",
    "ENTProcedureGuide",
    "FertilityAndIVFHelper",
    "SportsInjuryPreventor",
    "PharmacyInventoryManager",
    "PatientEngagementHub",
    "SurgicalInstrumentTracker",
    "HealthcareComplianceMonitor",
    "MedicalResearchDatabase",
    "TelemedicineConsultationPortal",
    "VaccineAdministrationLog",
    "AmbulanceDispatchSystem",
    "MedicalWasteManagement",
    "HospitalRoomAllocationSystem",
    "PatientFeedbackAnalyzer",
    "MedicalBillingAndCoding",
    "HealthcarePolicyLibrary",
    "ClinicalTrialManager",
    "MedicalEducationSimulator"
]

country_map = {
        "AFG": "Afghanistan",
        "ALA": "Åland Islands",
        "ALB": "Albania",
        "DZA": "Algeria",
        "ASM": "American Samoa",
        "AND": "Andorra",
        "AGO": "Angola",
        "AIA": "Anguilla",
        "ATA": "Antarctica",
        "ATG": "Antigua and Barbuda",
        "ARG": "Argentina",
        "ARM": "Armenia",
        "ABW": "Aruba",
        "AUS": "Australia",
        "AUT": "Austria",
        "AZE": "Azerbaijan",
        "BHS": "Bahamas",
        "BHR": "Bahrain",
        "BGD": "Bangladesh",
        "BRB": "Barbados",
        "BLR": "Belarus",
        "BEL": "Belgium",
        "BLZ": "Belize",
        "BEN": "Benin",
        "BMU": "Bermuda",
        "BTN": "Bhutan",
        "BOL": "Bolivia",
        "BES": "Bonaire, Sint Eustatius and Saba",
        "BIH": "Bosnia and Herzegovina",
        "BWA": "Botswana",
        "BVT": "Bouvet Island",
        "BRA": "Brazil",
        "IOT": "British Indian Ocean Territory",
        "BRN": "Brunei Darussalam",
        "BGR": "Bulgaria",
        "BFA": "Burkina Faso",
        "BDI": "Burundi",
        "KHM": "Cambodia",
        "CMR": "Cameroon",
        "CAN": "Canada",
        "CPV": "Cabo Verde",
        "CYM": "Cayman Islands",
        "CAF": "Central African Republic",
        "TCD": "Chad",
        "CHL": "Chile",
        "CHN": "China",
        "CXR": "Christmas Island",
        "CCK": "Cocos (Keeling) Islands",
        "COL": "Colombia",
        "COM": "Comoros",
        "COG": "Congo",
        "COD": "Congo",
        "COK": "Cook Islands",
        "CRI": "Costa Rica",
        "CIV": "Côte d'Ivoire",
        "HRV": "Croatia",
        "CUB": "Cuba",
        "CUW": "Curaçao",
        "CYP": "Cyprus",
        "CZE": "Czech Republic",
        "DNK": "Denmark",
        "DJI": "Djibouti",
        "DMA": "Dominica",
        "DOM": "Dominican Republic",
        "ECU": "Ecuador",
        "EGY": "Egypt",
        "SLV": "El Salvador",
        "GNQ": "Equatorial Guinea",
        "ERI": "Eritrea",
        "EST": "Estonia",
        "ETH": "Ethiopia",
        "FLK": "Falkland Islands (Malvinas)",
        "FRO": "Faroe Islands",
        "FJI": "Fiji",
        "FIN": "Finland",
        "FRA": "France",
        "GUF": "French Guiana",
        "PYF": "French Polynesia",
        "ATF": "French Southern Territories",
        "GAB": "Gabon",
        "GMB": "Gambia",
        "GEO": "Georgia",
        "DEU": "Germany",
        "GHA": "Ghana",
        "GIB": "Gibraltar",
        "GRC": "Greece",
        "GRL": "Greenland",
        "GRD": "Grenada",
        "GLP": "Guadeloupe",
        "GUM": "Guam",
        "GTM": "Guatemala",
        "GGY": "Guernsey",
        "GIN": "Guinea",
        "GNB": "Guinea-Bissau",
        "GUY": "Guyana",
        "HTI": "Haiti",
        "HMD": "Heard Island and McDonald Islands",
        "VAT": "Holy See",
        "HND": "Honduras",
        "HKG": "Hong Kong",
        "HUN": "Hungary",
        "ISL": "Iceland",
        "IND": "India",
        "IDN": "Indonesia",
        "IRN": "Iran",
        "IRQ": "Iraq",
        "IRL": "Ireland",
        "IMN": "Isle of Man",
        "ISR": "Israel",
        "ITA": "Italy",
        "JAM": "Jamaica",
        "JPN": "Japan",
        "JEY": "Jersey",
        "JOR": "Jordan",
        "KAZ": "Kazakhstan",
        "KEN": "Kenya",
        "KIR": "Kiribati",
        "PRK": "North Korea",
        "KOR": "South Korea",
        "KWT": "Kuwait",
        "KGZ": "Kyrgyzstan",
        "LAO": "Lao People's Democratic Republic",
        "LVA": "Latvia",
        "LBN": "Lebanon",
        "LSO": "Lesotho",
        "LBR": "Liberia",
        "LBY": "Libya",
        "LIE": "Liechtenstein",
        "LTU": "Lithuania",
        "LUX": "Luxembourg",
        "MAC": "Macao",
        "MKD": "Macedonia",
        "MDG": "Madagascar",
        "MWI": "Malawi",
        "MYS": "Malaysia",
        "MDV": "Maldives",
        "MLI": "Mali",
        "MLT": "Malta",
        "MHL": "Marshall Islands",
        "MTQ": "Martinique",
        "MRT": "Mauritania",
        "MUS": "Mauritius",
        "MYT": "Mayotte",
        "MEX": "Mexico",
        "FSM": "Micronesia",
        "MDA": "Moldova",
        "MCO": "Monaco",
        "MNG": "Mongolia",
        "MNE": "Montenegro",
        "MSR": "Montserrat",
        "MAR": "Morocco",
        "MOZ": "Mozambique",
        "MMR": "Myanmar",
        "NAM": "Namibia",
        "NRU": "Nauru",
        "NPL": "Nepal",
        "NLD": "Netherlands",
        "NCL": "New Caledonia",
        "NZL": "New Zealand",
        "NIC": "Nicaragua",
        "NER": "Niger",
        "NGA": "Nigeria",
        "NIU": "Niue",
        "NFK": "Norfolk Island",
        "MNP": "Northern Mariana Islands",
        "NOR": "Norway",
        "OMN": "Oman",
        "PAK": "Pakistan",
        "PLW": "Palau",
        "PSE": "Palestine, State of",
        "PAN": "Panama",
        "PNG": "Papua New Guinea",
        "PRY": "Paraguay",
        "PER": "Peru",
        "PHL": "Philippines",
        "PCN": "Pitcairn",
        "POL": "Poland",
        "PRT": "Portugal",
        "PRI": "Puerto Rico",
        "QAT": "Qatar",
        "REU": "Réunion",
        "ROU": "Romania",
        "RUS": "Russian Federation",
        "RWA": "Rwanda",
        "BLM": "Saint Barthélemy",
        "SHN": "Saint Helena",
        "KNA": "Saint Kitts and Nevis",
        "LCA": "Saint Lucia",
        "MAF": "Saint Martin (French part)",
        "SPM": "Saint Pierre and Miquelon",
        "VCT": "Saint Vincent and the Grenadines",
        "WSM": "Samoa",
        "SMR": "San Marino",
        "STP": "Sao Tome and Principe",
        "SAU": "Saudi Arabia",
        "SEN": "Senegal",
        "SRB": "Serbia",
        "SYC": "Seychelles",
        "SLE": "Sierra Leone",
        "SGP": "Singapore",
        "SXM": "Sint Maarten (Dutch part)",
        "SVK": "Slovakia",
        "SVN": "Slovenia",
        "SLB": "Solomon Islands",
        "SOM": "Somalia",
        "ZAF": "South Africa",
        "SGS": "South Georgia and the South Sandwich Islands",
        "SSD": "South Sudan",
        "ESP": "Spain",
        "LKA": "Sri Lanka",
        "SDN": "Sudan",
        "SUR": "Suriname",
        "SJM": "Svalbard and Jan Mayen",
        "SWZ": "Swaziland",
        "SWE": "Sweden",
        "CHE": "Switzerland",
        "SYR": "Syrian Arab Republic",
        "TWN": "Taiwan, Province of China",
        "TJK": "Tajikistan",
        "TZA": "Tanzania",
        "THA": "Thailand",
        "TLS": "Timor-Leste",
        "TGO": "Togo",
        "TKL": "Tokelau",
        "TON": "Tonga",
        "TTO": "Trinidad and Tobago",
        "TUN": "Tunisia",
        "TUR": "Turkey",
        "TKM": "Turkmenistan",
        "TCA": "Turks and Caicos Islands",
        "TUV": "Tuvalu",
        "UGA": "Uganda",
        "UKR": "Ukraine",
        "ARE": "United Arab Emirates",
        "GBR": "United Kingdom",
        "USA": "United States",
        "UMI": "United States Minor Outlying Islands",
        "URY": "Uruguay",
        "UZB": "Uzbekistan",
        "VUT": "Vanuatu",
        "VEN": "Venezuela",
        "VNM": "Viet Nam",
        "VGB": "Virgin Islands (British)",
        "VIR": "Virgin Islands (U.S.)",
        "WLF": "Wallis and Futuna",
        "ESH": "Western Sahara",
        "YEM": "Yemen",
        "ZMB": "Zambia",
        "ZWE": "Zimbabwe"
    }

# Function to generate a random data entry with component,event,day,times,country,country_code,
def generate_random_data_entry():
    return {
        "component": random.choice(modules),
        "event": random.choice(functions),
        "day": random_date(start_time, end_time),
        "times": str(random.randint(1, 2)),  # Random number of times between 1 and 2
        "country": random.choice(list(country_map.values())),
        "country_code": random.choice(list(country_map.keys())),
    }

# Generate random data entries and save it in a csv file
data_entries = [generate_random_data_entry() for _ in range(10000)]

# Define the CSV file path
csv_file_path = "random_usage_data.csv"

# Write the data to the CSV file
with open(csv_file_path, 'w', newline='', encoding='utf-8') as csvfile:
    # Define the CSV header based on the keys in the data entries
    fieldnames = data_entries[0].keys()
    
    # Create a CSV writer
    csv_writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    
    # Write the header
    csv_writer.writeheader()
    
    # Write each data entry
    for entry in data_entries:
        csv_writer.writerow(entry)

print(f"CSV file saved successfully at: {csv_file_path}")
